name: Build Push Update GitOps

on:
push:
branches:
- main

env:
DOCKER_IMAGE: manikandaprabu001/app-image
GITOPS_REPO: prabujack/git-tops-action

jobs:
build-and-deploy:


runs-on: ubuntu-latest

steps:

  - name: Checkout Application Source
    uses: actions/checkout@v4

  - name: Generate Image Tag
    id: tag
    run: |
      TAG=${GITHUB_SHA::7}
      echo "tag=$TAG" >> $GITHUB_OUTPUT

  - name: Login To Docker Hub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build Docker Image
    run: |
      docker build \
        -t $DOCKER_IMAGE:${{ steps.tag.outputs.tag }} \
        .

  - name: Push Docker Image
    run: |
      docker push $DOCKER_IMAGE:${{ steps.tag.outputs.tag }}

  - name: Clone GitOps Repository
    run: |
      git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/${GITOPS_REPO}.git

  - name: Update Deployment Manifest
    run: |
      cd gitops-repo

      sed -i "s|image: .*|image: $DOCKER_IMAGE:${{ steps.tag.outputs.tag }}|g" \
      apps/nginx/deployment.yaml

      cat apps/nginx/deployment.yaml

  - name: Commit Changes
    run: |
      cd gitops-repo

      git config user.name "prabujack"
      git config user.email "prabujack599@gmail.com"

      git add .

      git commit -m "Update image tag to ${{ steps.tag.outputs.tag }}" || echo "No changes"

      git push
